# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import csv

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 532)
        font = QtGui.QFont()
        font.setPointSize(18)
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.registration = QtWidgets.QLabel(self.centralwidget)
        self.registration.setGeometry(QtCore.QRect(0, 50, 800, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.registration.setFont(font)
        self.registration.setStyleSheet("")
        self.registration.setTextFormat(QtCore.Qt.AutoText)
        self.registration.setScaledContents(False)
        self.registration.setAlignment(QtCore.Qt.AlignCenter)
        self.registration.setWordWrap(False)
        self.registration.setOpenExternalLinks(False)
        self.registration.setObjectName("registration")
        self.firstname = QtWidgets.QLabel(self.centralwidget)
        self.firstname.setGeometry(QtCore.QRect(130, 120, 151, 30))
        self.firstname.setObjectName("firstname")
        self.firstname_input = QtWidgets.QLineEdit(self.centralwidget)
        self.firstname_input.setGeometry(QtCore.QRect(280, 120, 411, 30))
        self.firstname_input.setObjectName("firstname_input")
        self.surname = QtWidgets.QLabel(self.centralwidget)
        self.surname.setGeometry(QtCore.QRect(130, 190, 151, 30))
        self.surname.setObjectName("surname")
        self.surname_input = QtWidgets.QLineEdit(self.centralwidget)
        self.surname_input.setGeometry(QtCore.QRect(280, 190, 411, 30))
        self.surname_input.setObjectName("surname_input")
        self.male = QtWidgets.QRadioButton(self.centralwidget)
        self.male.setGeometry(QtCore.QRect(280, 250, 100, 20))
        self.male.setObjectName("male")
        self.female = QtWidgets.QRadioButton(self.centralwidget)
        self.female.setGeometry(QtCore.QRect(280, 280, 100, 20))
        self.female.setObjectName("female")
        self.gender = QtWidgets.QLabel(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(130, 255, 151, 30))
        self.gender.setObjectName("gender")
        self.agreement_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.agreement_checkBox.setGeometry(QtCore.QRect(530, 334, 16, 30))
        self.agreement_checkBox.setText("")
        self.agreement_checkBox.setObjectName("agreement_checkBox")
        self.agreement = QtWidgets.QLabel(self.centralwidget)
        self.agreement.setGeometry(QtCore.QRect(130, 330, 400, 30))
        self.agreement.setObjectName("agreement")
        self.birth_date_widget = QtWidgets.QDateEdit(self.centralwidget)
        self.birth_date_widget.setGeometry(QtCore.QRect(580, 260, 110, 22))
        self.birth_date_widget.setObjectName("birth_date_widget")
        self.birth_date = QtWidgets.QLabel(self.centralwidget)
        self.birth_date.setGeometry(QtCore.QRect(420, 255, 151, 30))
        self.birth_date.setObjectName("birth_date")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 410, 261, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.submit_form)

    def submit_form(self):
        
        firstname = self.firstname_input.text()
        surname = self.surname_input.text()
        gender = "Male" if self.male.isChecked() else "Female"
        birth_date = self.birth_date_widget.date().toString("yyyy-MM-dd")

        if not self.agreement_checkBox.isChecked():
            return

        if not firstname or not surname or not gender or not birth_date :
            return
        with open("data.csv", "a", newline="") as file:
            writer = csv.writer(file)
            writer.writerow([firstname, surname, gender, birth_date])


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registration.setText(_translate("MainWindow", "Registration"))
        self.firstname.setText(_translate("MainWindow", "First Name:"))
        self.surname.setText(_translate("MainWindow", "Surname:"))
        self.male.setText(_translate("MainWindow", "Male"))
        self.female.setText(_translate("MainWindow", "Female"))
        self.gender.setText(_translate("MainWindow", "Gender:"))
        self.agreement.setText(_translate("MainWindow", "I agree to the terms and conditions:"))
        self.birth_date.setText(_translate("MainWindow", "Birth date:"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
